import type { PaymentMethod } from '@/lib/payments';

export type CheckoutLocale = 'ar' | 'en';

type PaymentCopy = {
  label: string;
  badge: string;
  description: string;
  note: string;
  cta: (total: string) => string;
};

export const checkoutCopy = {
  ar: {
    dir: 'rtl' as const,
    backToCart: 'الرجوع للسلة',
    kicker: 'الخطوة الأخيرة',
    title: 'إتمام الطلب',
    intro: 'أكمل بياناتك بوضوح، اختر طريقة الدفع، وراجع الإجمالي النهائي قبل تأكيد الطلب. سنؤكد طلبك على واتساب بعد التسجيل.',
    steps: ['بياناتك', 'التوصيل', 'الدفع', 'التأكيد'],
    trustItems: ['تأكيد واتساب', 'إجمالي واضح', 'تحديث الطلب بسهولة'],
    contactTitle: 'بيانات التواصل',
    fullName: 'الاسم بالكامل *',
    fullNamePlaceholder: 'اكتب اسمك بالكامل',
    phone: 'رقم الهاتف *',
    deliveryTitle: 'عنوان التوصيل',
    governorate: 'المحافظة *',
    chooseGovernorate: 'اختر المحافظة',
    city: 'المدينة *',
    chooseCity: 'اختر المدينة',
    address: 'العنوان التفصيلي *',
    addressPlaceholder: 'اسم الشارع، رقم العمارة، الدور، الشقة، أقرب علامة مميزة',
    notes: 'ملاحظات اختيارية',
    notesPlaceholder: 'أي تعليمات خاصة للتوصيل',
    paymentTitle: 'طريقة الدفع',
    paymentIntro: 'كل طريقة دفع توضّح المطلوب قبل التأكيد: دفع عند الاستلام، تحويل مع Screenshot، أو متابعة ValU.',
    secureBadge: 'دفع آمن',
    transferNumber: 'رقم التحويل:',
    copy: 'نسخ',
    transferCopied: 'تم نسخ رقم التحويل',
    valuContact: 'رقم التواصل لتأكيد ValU:',
    processing: 'جاري تسجيل الطلب...',
    summaryTitle: 'ملخص الطلب النهائي',
    deliveryQuote: 'عرض التوصيل',
    calculatingDelivery: 'جاري حساب التوصيل...',
    freeShippingApplied: 'تم تطبيق الشحن المجاني',
    chooseAreaForDelivery: 'اختر المحافظة والمدينة لحساب التوصيل.',
    size: 'المقاس',
    color: 'اللون',
    quantity: 'الكمية',
    coupon: 'كود الخصم',
    apply: 'تطبيق',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    delivery: 'التوصيل',
    free: 'مجاني',
    codFee: 'رسوم الدفع عند الاستلام',
    total: 'الإجمالي',
    totalNote: 'هذا هو الإجمالي النهائي قبل التأكيد، ويشمل المنتجات والشحن والخصومات حسب المنطقة المختارة.',
    noCodFeeNote: 'لا يتم إضافة رسوم الدفع عند الاستلام على Instapay أو Vodafone Cash أو ValU.',
    emptyCart: 'السلة فارغة',
    unsupportedArea: 'اختر منطقة توصيل مدعومة قبل تأكيد الطلب.',
    couponError: 'تعذر التحقق من الكود الآن',
    orderSaved: 'تم تسجيل الطلب بنجاح',
    successKicker: 'تم استلام الطلب',
    successTitle: 'تم استلام طلبك بنجاح',
    orderNumber: 'رقم الطلب',
    orderCopied: 'تم نسخ رقم الطلب',
    whatsappConfirm: 'فتح واتساب لتأكيد الطلب',
    trackOrder: 'متابعة حالة الطلب',
    continueShopping: 'متابعة التسوق',
    validation: {
      'Full name must be at least 3 characters': 'اكتب الاسم بالكامل بحد أدنى 3 حروف.',
      'Full name must be less than 100 characters': 'الاسم طويل جدًا.',
      'Invalid Egyptian phone number (e.g., 01XXXXXXXX)': 'اكتب رقم هاتف مصري صحيح مثل 01XXXXXXXXX.',
      'Please select a governorate': 'اختر المحافظة.',
      'Please select a city': 'اختر المدينة.',
      'Address must be at least 10 characters': 'اكتب عنوانًا أوضح بحد أدنى 10 حروف.',
      'Address must be less than 300 characters': 'العنوان طويل جدًا.',
      'Notes must be less than 500 characters': 'الملاحظات طويلة جدًا.',
    } as Record<string, string>,
    payments: {
      cod: {
        label: 'الدفع عند الاستلام',
        badge: 'بدون تحويل',
        description: 'ادفع نقدًا عند وصول الطلب. لا تحتاج لتحويل أي مبلغ قبل الاستلام.',
        note: 'الخطوة التالية: سنراجع تفاصيل الطلب والعنوان معك على واتساب قبل التجهيز والشحن.',
        cta: (total: string) => `تأكيد الطلب — ${total}`,
      },
      instapay: {
        label: 'Instapay / تحويل بنكي',
        badge: 'يحتاج إثبات تحويل',
        description: 'حوّل الإجمالي النهائي على رقم NEXORA، ثم أرسل Screenshot التحويل لتأكيد الدفع.',
        note: 'الخطوة التالية: بعد تسجيل الطلب، افتح واتساب وأرسل Screenshot التحويل مع رقم الطلب. يبدأ التجهيز بعد تأكيد الدفع.',
        cta: (total: string) => `تسجيل الطلب وإرسال إثبات الدفع — ${total}`,
      },
      vodafone_cash: {
        label: 'Vodafone Cash',
        badge: 'يحتاج إثبات تحويل',
        description: 'حوّل الإجمالي النهائي على Vodafone Cash، ثم أرسل Screenshot واضح لتأكيد الدفع.',
        note: 'الخطوة التالية: أرسل Screenshot يظهر المبلغ ورقم العملية بوضوح حتى نؤكد الدفع بسرعة.',
        cta: (total: string) => `تسجيل الطلب وإرسال إثبات الدفع — ${total}`,
      },
      valu: {
        label: 'ValU Installments',
        badge: 'تأكيد يدوي',
        description: 'سجّل الطلب الآن، وسيتواصل فريق NEXORA معك لتأكيد خطة التقسيط المتاحة مع ValU.',
        note: 'الخطوة التالية: لا تقم بأي تحويل. سنؤكد تفاصيل ValU يدويًا على واتساب قبل تجهيز الطلب.',
        cta: (total: string) => `تسجيل الطلب والتواصل لتأكيد التقسيط — ${total}`,
      },
    } satisfies Record<PaymentMethod, PaymentCopy>,
    success: {
      cod: 'تم استلام طلبك بنظام الدفع عند الاستلام. سنؤكد معك التفاصيل على واتساب قبل التجهيز.',
      instapay: 'تم تسجيل طلبك. لإكمال التأكيد، أرسل Screenshot تحويل Instapay على واتساب مع رقم الطلب.',
      vodafone_cash: 'تم تسجيل طلبك. أرسل Screenshot تحويل Vodafone Cash ويجب أن يظهر رقم العملية والمبلغ بوضوح.',
      valu: 'تم تسجيل طلبك بنظام ValU. سنتواصل معك لتأكيد تفاصيل التقسيط قبل التجهيز.',
    } satisfies Record<PaymentMethod, string>,
  },
  en: {
    dir: 'ltr' as const,
    backToCart: 'Back to cart',
    kicker: 'Final step',
    title: 'Checkout',
    intro: 'Complete your details, choose how you want to pay, and review the final total before placing the order. We will confirm everything on WhatsApp afterward.',
    steps: ['Details', 'Delivery', 'Payment', 'Confirmation'],
    trustItems: ['WhatsApp confirmation', 'Clear final total', 'Easy order updates'],
    contactTitle: 'Contact details',
    fullName: 'Full name *',
    fullNamePlaceholder: 'Enter your full name',
    phone: 'Phone number *',
    deliveryTitle: 'Delivery address',
    governorate: 'Governorate *',
    chooseGovernorate: 'Select governorate',
    city: 'City *',
    chooseCity: 'Select city',
    address: 'Street address *',
    addressPlaceholder: 'Street name, building, floor, apartment, nearest landmark',
    notes: 'Optional notes',
    notesPlaceholder: 'Any delivery instructions',
    paymentTitle: 'Payment method',
    paymentIntro: 'Each option shows exactly what happens next: cash on delivery, transfer with screenshot, or ValU follow-up.',
    secureBadge: 'Secure checkout',
    transferNumber: 'Transfer number:',
    copy: 'Copy',
    transferCopied: 'Transfer number copied',
    valuContact: 'ValU confirmation contact:',
    processing: 'Placing order...',
    summaryTitle: 'Final order summary',
    deliveryQuote: 'Delivery quote',
    calculatingDelivery: 'Calculating delivery...',
    freeShippingApplied: 'Free shipping applied',
    chooseAreaForDelivery: 'Select governorate and city to calculate delivery.',
    size: 'Size',
    color: 'Color',
    quantity: 'Qty',
    coupon: 'Coupon code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery: 'Delivery',
    free: 'Free',
    codFee: 'Cash on delivery fee',
    total: 'Total',
    totalNote: 'This is the final total before confirmation, including products, delivery, and discounts for the selected area.',
    noCodFeeNote: 'Cash on delivery fees are not added to Instapay, Vodafone Cash, or ValU orders.',
    emptyCart: 'Your cart is empty',
    unsupportedArea: 'Please choose a supported delivery area before placing the order.',
    couponError: 'Could not validate the coupon right now.',
    orderSaved: 'Order placed successfully',
    successKicker: 'Order received',
    successTitle: 'Your order has been received',
    orderNumber: 'Order number',
    orderCopied: 'Order number copied',
    whatsappConfirm: 'Open WhatsApp to confirm',
    trackOrder: 'Track order',
    continueShopping: 'Continue shopping',
    validation: {
      'Full name must be at least 3 characters': 'Full name must be at least 3 characters.',
      'Full name must be less than 100 characters': 'Full name must be less than 100 characters.',
      'Invalid Egyptian phone number (e.g., 01XXXXXXXX)': 'Enter a valid Egyptian phone number, e.g. 01XXXXXXXXX.',
      'Please select a governorate': 'Please select a governorate.',
      'Please select a city': 'Please select a city.',
      'Address must be at least 10 characters': 'Address must be at least 10 characters.',
      'Address must be less than 300 characters': 'Address must be less than 300 characters.',
      'Notes must be less than 500 characters': 'Notes must be less than 500 characters.',
    } as Record<string, string>,
    payments: {
      cod: {
        label: 'Cash on Delivery',
        badge: 'No transfer',
        description: 'Pay in cash when the order arrives. No transfer is needed before delivery.',
        note: 'Next step: we will confirm the order details and address with you on WhatsApp before preparation and dispatch.',
        cta: (total: string) => `Place order — ${total}`,
      },
      instapay: {
        label: 'Instapay / Bank Transfer',
        badge: 'Proof required',
        description: 'Transfer the final total to NEXORA, then send the payment screenshot to confirm the transfer.',
        note: 'Next step: after placing the order, open WhatsApp and send the transfer screenshot with your order number. Preparation starts after payment confirmation.',
        cta: (total: string) => `Place order and send proof — ${total}`,
      },
      vodafone_cash: {
        label: 'Vodafone Cash',
        badge: 'Proof required',
        description: 'Send the final total to Vodafone Cash, then send a clear screenshot to confirm payment.',
        note: 'Next step: send a screenshot that clearly shows the amount and transaction reference so we can confirm quickly.',
        cta: (total: string) => `Place order and send proof — ${total}`,
      },
      valu: {
        label: 'ValU Installments',
        badge: 'Manual confirmation',
        description: 'Place the order now and the NEXORA team will contact you to confirm the available ValU installment plan.',
        note: 'Next step: do not transfer any amount. We will manually confirm ValU details on WhatsApp before preparing the order.',
        cta: (total: string) => `Place order and confirm installments — ${total}`,
      },
    } satisfies Record<PaymentMethod, PaymentCopy>,
    success: {
      cod: 'Your cash-on-delivery order has been received. We will confirm the details on WhatsApp before preparation.',
      instapay: 'Your order has been placed. To complete confirmation, send the Instapay transfer screenshot on WhatsApp with your order number.',
      vodafone_cash: 'Your order has been placed. Send the Vodafone Cash screenshot on WhatsApp and make sure the transaction number and amount are visible.',
      valu: 'Your ValU order has been placed. We will contact you on WhatsApp to confirm installment details before preparation.',
    } satisfies Record<PaymentMethod, string>,
  },
};

export function getCheckoutCopy(locale: CheckoutLocale) {
  return checkoutCopy[locale] || checkoutCopy.en;
}

export function translateCheckoutError(message: unknown, locale: CheckoutLocale) {
  const raw = String(message || '');
  const copy = getCheckoutCopy(locale);
  return copy.validation[raw] || raw;
}
