/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Download, RefreshCw, TrendingUp, Users, MessageCircle } from 'lucide-react';
import { formatPrice } from '@/lib/utils';

function csvEscape(value: unknown) { return `"${String(value ?? '').replace(/"/g, '""')}"`; }

export default function AdminReports() {
  const [data, setData] = useState<any>({ campaigns: [], summary: {} });
  const [isLoading, setIsLoading] = useState(true);
  const load = async () => { setIsLoading(true); try { const { getCampaignReports } = await import('@/lib/supabase/db'); setData(await getCampaignReports()); } finally { setIsLoading(false); } };
  useEffect(() => { void load(); }, []);
  const campaigns = useMemo(() => data.campaigns || [], [data.campaigns]);
  const totals = useMemo(() => campaigns.reduce((acc: any, row: any) => ({ visitors: acc.visitors + Number(row.visitors || 0), leads: acc.leads + Number(row.leads || 0), whatsapp: acc.whatsapp + Number(row.whatsappClicks || 0), orders: acc.orders + Number(row.orders || 0), revenue: acc.revenue + Number(row.revenue || 0) }), { visitors: 0, leads: 0, whatsapp: 0, orders: 0, revenue: 0 }), [campaigns]);
  const exportCsv = () => { const rows = [['source','campaign','visitors','leads','whatsapp_clicks','orders','revenue'], ...campaigns.map((r: any) => [r.source, r.campaign, r.visitors, r.leads, r.whatsappClicks, r.orders, r.revenue])]; const blob = new Blob([rows.map((row) => row.map(csvEscape).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `nexora-campaign-report-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-bold tracking-tight text-[#FFF0E1]">Growth Reports</h1><p className="mt-1 text-sm text-[#BCAEA0]">Visitors, leads, WhatsApp clicks, orders, and revenue by campaign/source.</p></div><div className="flex gap-2"><button onClick={exportCsv} className="nexora-button"><Download className="h-4 w-4" />Export</button><button onClick={load} className="nexora-button"><RefreshCw className="h-4 w-4" />Refresh</button></div></div>{isLoading && <div className="studio-card p-4 text-sm text-[#BCAEA0]">Loading reports...</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Visitors" value={String(totals.visitors)} helper="Tracked campaign visitors." icon={Users} /><Metric label="Leads" value={String(totals.leads)} helper="Private list, WhatsApp, checkout leads." icon={TrendingUp} /><Metric label="WhatsApp" value={String(totals.whatsapp)} helper="Contact intent clicks." icon={MessageCircle} /><Metric label="Orders" value={String(totals.orders)} helper="Orders matched to attribution." icon={BarChart3} /><Metric label="Revenue" value={formatPrice(totals.revenue)} helper="Attributed COD order value." icon={TrendingUp} /></div><div className="studio-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-[#17110F]"><tr>{['Source','Campaign','Visitors','Leads','WhatsApp','Orders','Revenue','Lead rate'].map((h) => <th key={h} className="p-4 text-[10px] uppercase tracking-[0.18em] text-[#BCAEA0]">{h}</th>)}</tr></thead><tbody>{campaigns.length ? campaigns.map((row: any) => { const rate = Number(row.visitors || 0) ? Math.round((Number(row.leads || 0) / Number(row.visitors || 0)) * 100) : 0; return <tr key={`${row.source}-${row.campaign}`} className="border-t border-[#332923]/70"><td className="p-4 text-xs font-semibold text-[#D2B48C]">{row.source || 'direct'}</td><td className="p-4 text-xs text-[#FFF0E1]">{row.campaign || 'no campaign'}</td><td className="p-4 text-xs text-[#BCAEA0]">{row.visitors || 0}</td><td className="p-4 text-xs text-[#BCAEA0]">{row.leads || 0}</td><td className="p-4 text-xs text-[#BCAEA0]">{row.whatsappClicks || 0}</td><td className="p-4 text-xs text-[#BCAEA0]">{row.orders || 0}</td><td className="p-4 text-xs text-[#D2B48C]">{formatPrice(Number(row.revenue || 0))}</td><td className="p-4 text-xs text-[#BCAEA0]">{rate}%</td></tr>; }) : <tr><td colSpan={8} className="p-8 text-center text-sm text-[#BCAEA0]">No report data yet.</td></tr>}</tbody></table></div></div></div>;
}
function Metric({ label, value, helper, icon: Icon }: { label: string; value: string; helper: string; icon: React.ElementType }) { return <div className="studio-card p-5"><div className="mb-3 flex items-center justify-between"><Icon className="h-5 w-5 text-[#D2B48C]" /><span className="text-[10px] uppercase tracking-[0.18em] text-[#BCAEA0]">{label}</span></div><p className="text-2xl font-bold text-[#FFF0E1]">{value}</p><p className="mt-2 text-xs leading-6 text-[#BCAEA0]">{helper}</p></div>; }
